export const THEME_PRESETS = [
  {
    name: 'Calm Light',
    description: 'Bright, gentle neutrals with soft rose highlights.',
    palette: {
      light: {
        primary: '#c8748f',
        secondary: '#7f6c9f',
        accent: '#f2d3c2',
        surface: '#fdf6f3',
        card: '#f9f1ed',
        muted: '#6a5c5f',
        text: '#2f2729',
        gradientFrom: '#f7d4dd',
        gradientTo: '#c8d8d0',
        glow: '#f2c4cf',
      },
      dark: {
        primary: '#f0b7c6',
        secondary: '#b7accf',
        accent: '#d4b7a6',
        surface: '#14161b',
        card: '#1d2027',
        muted: '#b8b1ad',
        text: '#ece8e4',
        gradientFrom: '#7c8c9f',
        gradientTo: '#c59aa8',
        glow: '#9eb8c6',
      },
    },
  },
  {
    name: 'Deep Night',
    description: 'Moody dark base with clean lilac and teal accents.',
    palette: {
      light: {
        primary: '#6f7cd4',
        secondary: '#213547',
        accent: '#d9e1f8',
        surface: '#f7f8fb',
        card: '#eef0f6',
        muted: '#4c5568',
        text: '#111827',
        gradientFrom: '#e1e6ff',
        gradientTo: '#c1d7e5',
        glow: '#a3b2f0',
      },
      dark: {
        primary: '#9ca8ff',
        secondary: '#e3e7ee',
        accent: '#2d374d',
        surface: '#0e1017',
        card: '#161926',
        muted: '#9aa3b8',
        text: '#f2f6ff',
        gradientFrom: '#1c233b',
        gradientTo: '#2f3a73',
        glow: '#5060ff',
      },
    },
  },
];
