export const THEME_PRESETS = [
  {
    name: 'Rose Garden',
    description: 'Romantic blush with soft grays and warm glow.',
    palette: {
      light: {
        primary: '#d46a92',
        secondary: '#8c7fb1',
        accent: '#f2d8ce',
        surface: '#fdf7f4',
        card: '#f7efea',
        muted: '#6f6165',
        text: '#2f252a',
        gradientFrom: '#f7d2de',
        gradientTo: '#d6e2d6',
        glow: '#f6c6d5',
      },
      dark: {
        primary: '#f1b8c8',
        secondary: '#b8add8',
        accent: '#d7bfae',
        surface: '#15171f',
        card: '#1e2129',
        muted: '#bdb6b2',
        text: '#f3eeea',
        gradientFrom: '#7b8aa6',
        gradientTo: '#d0a0ae',
        glow: '#9ebed1',
      },
    },
  },
  {
    name: 'Sea Glass',
    description: 'Coastal teals, crisp neutrals, and airy surfaces.',
    palette: {
      light: {
        primary: '#2fa4a9',
        secondary: '#5a6fb0',
        accent: '#b7e3df',
        surface: '#f4fbfa',
        card: '#e7f4f2',
        muted: '#4c6467',
        text: '#123035',
        gradientFrom: '#b8e7e0',
        gradientTo: '#d7e0f3',
        glow: '#a4d7d1',
      },
      dark: {
        primary: '#75d0d1',
        secondary: '#8ca1e0',
        accent: '#93c9c4',
        surface: '#0f1619',
        card: '#172026',
        muted: '#93a6a8',
        text: '#e5f5f7',
        gradientFrom: '#5f7fa6',
        gradientTo: '#79c0bc',
        glow: '#5ab5b1',
      },
    },
  },
  {
    name: 'Forest Dusk',
    description: 'Grounded greens with sunset coral accents.',
    palette: {
      light: {
        primary: '#2f7c74',
        secondary: '#4f5c7d',
        accent: '#ffc9a9',
        surface: '#f7f5f1',
        card: '#efe9e1',
        muted: '#4b4b44',
        text: '#1f221c',
        gradientFrom: '#cbe2d4',
        gradientTo: '#f8d5c4',
        glow: '#d1c0a8',
      },
      dark: {
        primary: '#6fc3b7',
        secondary: '#8fa1c7',
        accent: '#ffb48f',
        surface: '#101411',
        card: '#161d17',
        muted: '#a0a39b',
        text: '#edf0eb',
        gradientFrom: '#4a675e',
        gradientTo: '#b1856a',
        glow: '#7da694',
      },
    },
  },
  {
    name: 'Minimal Noir',
    description: 'High-contrast monochrome with electric accents.',
    palette: {
      light: {
        primary: '#5565f5',
        secondary: '#111827',
        accent: '#cdd5ff',
        surface: '#f8f9fd',
        card: '#eef0fb',
        muted: '#4b5563',
        text: '#111827',
        gradientFrom: '#dfe3ff',
        gradientTo: '#c7cfe9',
        glow: '#9aa6ff',
      },
      dark: {
        primary: '#7d8bff',
        secondary: '#e5e7eb',
        accent: '#2b2f45',
        surface: '#0c0d14',
        card: '#121320',
        muted: '#9ea8bd',
        text: '#f5f7ff',
        gradientFrom: '#1f2640',
        gradientTo: '#37408c',
        glow: '#4b5bff',
      },
    },
  },
];
