import React from 'react';
import { Activity } from 'lucide-react';
import PoseIcon from './PoseIcon';
import getLevelColor from '../utils/getLevelColor';
import { SEQUENCE_METHODS } from '../constants/sequence';

const PrintLayout = ({ sequence, params }) => (
  <div className="print-only-container bg-white text-black min-h-screen p-8">
    <div className="text-center mb-8 border-b border-gray-200 pb-6">
      <div className="flex items-center justify-center gap-2 mb-2">
        <Activity size={24} />
        <h1 className="text-4xl font-serif font-bold">ZenFlow</h1>
      </div>
      <h2 className="text-xl font-medium text-gray-600 mb-1">
        {params.style} Flow • {params.difficulty}
      </h2>
      <div className="flex justify-center gap-6 text-sm text-gray-500">
        <span>{params.duration} mins</span>
        <span>{sequence.length} poses</span>
        {params.method === SEQUENCE_METHODS.PEAK && <span>Peak Pose Focus</span>}
      </div>
    </div>

    <div className="grid grid-cols-2 gap-6">
      {sequence.map((pose, idx) => (
        <div key={pose.uniqueId} className="flex gap-4 p-4 border border-gray-200 rounded-xl break-inside-avoid">
          <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center shrink-0 text-gray-700">
            <PoseIcon category={pose.category} className="w-8 h-8" />
          </div>
          <div className="flex-1">
            <div className="flex justify-between items-start mb-1">
              <h3 className="font-bold text-lg">{pose.name}</h3>
              <span className={`text-xs px-2 py-0.5 rounded font-bold ${getLevelColor(pose.difficulty).replace('dark:', '')}`}>
                Lvl {pose.difficulty}
              </span>
            </div>
            <p className="text-sm italic text-gray-500 mb-2 font-serif">{pose.sanskrit}</p>
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-gray-400 mb-2">
              <span>{pose.category}</span>
              <span>•</span>
              <span>{pose.duration}</span>
            </div>
            <p className="text-sm text-gray-700 leading-relaxed">{pose.teachingCue}</p>
          </div>
          <div className="text-2xl font-mono font-bold text-gray-200 w-8 text-right">{idx + 1}</div>
        </div>
      ))}
    </div>

    <div className="mt-12 text-center text-xs text-gray-400 border-t border-gray-100 pt-6">
      Generated by ZenFlow • Namaste
    </div>
  </div>
);

export default PrintLayout;
